# Generated by Django 4.0.4 on 2022-05-25 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('Name', models.CharField(max_length=200, null=True)),
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Gpa', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('Level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200)),
                ('Department', models.CharField(choices=[('General', 'General'), ('CS', 'CS'), ('IS', 'IS'), ('DS', 'DS'), ('AI', 'AI'), ('IT', 'IT')], max_length=200)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Birth_Date', models.DateField()),
            ],
        ),
    ]
