# Generated by Django 4.0.4 on 2022-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Department',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='Gender',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='Level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='Status',
            field=models.CharField(max_length=200),
        ),
    ]
