# Generated by Django 4.0.4 on 2022-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_department_alter_members_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Department',
            field=models.CharField(max_length=200),
        ),
    ]
