# Generated by Django 4.0.4 on 2022-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
