# Generated by Django 4.0.4 on 2022-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Status',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200),
        ),
    ]
