# Generated by Django 4.0.4 on 2022-05-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Department',
            field=models.CharField(choices=[('IS', 'IS'), ('CS', 'CS'), ('AI', 'AI'), ('DS', 'DS'), ('IT', 'IT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='Level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20),
        ),
    ]
